### ISSUE TITLE
Daily action timeline

### ISSUE THREAD

**Issue by lfvperes** [lfvperes/jaguar-bot#41]
### Schedule
1. Search for new URLs and store them - _Less frequent, may be called when the list starts getting short (?) or once a week_
  - Add items to `unfiltered`
2. Filter URLs with CV - _Less frequent, may be called when the list starts getting short (?) or once a week_
  - Change (some) items from `unfiltered` to `filtered/not_posted`
  - Some items will remain in `unfiltered`
  - filter_url() in Bot.js
3. Post from selected URL - _More frequent (daily)_
  - Download image
  - Resize* if needed
  - Upload image as blob
  - Post image on Twitter
  - Delete image (locally)
  - Change **one** item from `filtered/not_posted` to `filtered/posted`
  - Verify if the URL list needs more input

**Not really resizing as a unity factor will be used*
### Requirements
Heroku provides 1000 free hours per month, being more than enough to run a bot 24/7 for 30 days (720 hours per month) using a **worker dyno**. However it is interesting to find a way to minimize this use, i. e. by using an Add-on like **Scheduler** or the **Advanced Scheduler**.
### Tasks
- [x] Configure environment variables
- [x] Configure Heroku worker dyno
- [x] Configure Heroku Scheduler Add-on and turn off worker dyno
- [ ] Separate scripts for each item of the Schedule to allow for frequency control
- [ ] Implement a monitoring scheme (i. e. sending updates as DM)
